services:
  namespace-postgres:
    container_name: namespace-postgres
    image: postgis/postgis:16-3.4-alpine
    shm_size: 2g
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: namespace_dev
    ports:
      - 5434:5432
    volumes:
      - ./.docker-db:/docker-entrypoint-initdb.d
