services:
  namespace-postgres:
    container_name: namespace-postgres
    image: postgis/postgis:16-3.4-alpine
    shm_size: 2g
    restart: always
    environment:
      POSTGRES_USER: ${CORE_DB_USER}
      POSTGRES_PASSWORD: ${CORE_DB_PASSWORD}
      POSTGRES_DB: ${CORE_DB_NAME}
    ports:
      - ${CORE_DB_PORT}:5432
    volumes:
      - ./.docker-db:/docker-entrypoint-initdb.d
#
