services:
  postgres:
    container_name: whiteroom-postgres
    image: postgis/postgis:16-3.4-alpine
    shm_size: 2g
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whiteroom_dev
    ports:
      - 5432:5432
  redis:
    container_name: whiteroom-redis
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - 6379:6379
