/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthMe200CreatedAt } from './getAuthMe200CreatedAt';
import type { GetAuthMe200RolesItem } from './getAuthMe200RolesItem';
import type { GetAuthMe200ProfilePictureUrl } from './getAuthMe200ProfilePictureUrl';

export type GetAuthMe200 = {
  id: string;
  createdAt: GetAuthMe200CreatedAt;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /**
   * @minLength 10
   * @maxLength 10
   * @pattern ^\d{10}$
   */
  phone: string;
  email: string;
  /** @minItems 1 */
  roles: GetAuthMe200RolesItem[];
  profilePictureUrl: GetAuthMe200ProfilePictureUrl;
};
