/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */

export type GetAuthMe200RolesItem =
  (typeof GetAuthMe200RolesItem)[keyof typeof GetAuthMe200RolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuthMe200RolesItem = {
  user: 'user',
  admin: 'admin',
} as const;
