/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */

export type GetAddressesAddressId200AddressType =
  (typeof GetAddressesAddressId200AddressType)[keyof typeof GetAddressesAddressId200AddressType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAddressesAddressId200AddressType = {
  address: 'address',
  coordinates: 'coordinates',
} as const;
