/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthMe200CreatedAtAllOf } from './getAuthMe200CreatedAtAllOf';

export type GetAuthMe200CreatedAt = GetAuthMe200CreatedAtAllOf & string;
