/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { GetAddressesAddressId200Address } from './getAddressesAddressId200Address';

export type GetAddressesAddressId200 = {
  address: GetAddressesAddressId200Address;
};
