/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { GetDatatablesUsers200ItemsItemCreatedAt } from './getDatatablesUsers200ItemsItemCreatedAt';
import type { GetDatatablesUsers200ItemsItemRolesItem } from './getDatatablesUsers200ItemsItemRolesItem';
import type { GetDatatablesUsers200ItemsItemProfilePictureUrl } from './getDatatablesUsers200ItemsItemProfilePictureUrl';

export type GetDatatablesUsers200ItemsItem = {
  id: string;
  createdAt: GetDatatablesUsers200ItemsItemCreatedAt;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /**
   * @minLength 10
   * @maxLength 10
   * @pattern ^\d{10}$
   */
  phone: string;
  email: string;
  /** @minItems 1 */
  roles: GetDatatablesUsers200ItemsItemRolesItem[];
  profilePictureUrl: GetDatatablesUsers200ItemsItemProfilePictureUrl;
};
