/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { GetDatatablesUsersSortItem } from './getDatatablesUsersSortItem';
import type { GetDatatablesUsersFuzzyItem } from './getDatatablesUsersFuzzyItem';

export type GetDatatablesUsersParams = {
  count?: number;
  skip?: number;
  sort?: GetDatatablesUsersSortItem[];
  filter?: { [key: string]: unknown };
  fuzzy?: GetDatatablesUsersFuzzyItem[];
  includeItemsCount?: boolean;
};
