/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */

export type GetDatatablesUsers200ItemsItemRolesItem =
  (typeof GetDatatablesUsers200ItemsItemRolesItem)[keyof typeof GetDatatablesUsers200ItemsItemRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetDatatablesUsers200ItemsItemRolesItem = {
  user: 'user',
  admin: 'admin',
} as const;
