/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { GetGoogleAutocomplete200SuggestionsItemStreetName } from './getGoogleAutocomplete200SuggestionsItemStreetName';
import type { GetGoogleAutocomplete200SuggestionsItemStreetNumber } from './getGoogleAutocomplete200SuggestionsItemStreetNumber';
import type { GetGoogleAutocomplete200SuggestionsItemStreetPrefix } from './getGoogleAutocomplete200SuggestionsItemStreetPrefix';
import type { GetGoogleAutocomplete200SuggestionsItemStreetSuffix } from './getGoogleAutocomplete200SuggestionsItemStreetSuffix';
import type { GetGoogleAutocomplete200SuggestionsItemUnitNumber } from './getGoogleAutocomplete200SuggestionsItemUnitNumber';
import type { GetGoogleAutocomplete200SuggestionsItemStateCode } from './getGoogleAutocomplete200SuggestionsItemStateCode';
import type { GetGoogleAutocomplete200SuggestionsItemCounty } from './getGoogleAutocomplete200SuggestionsItemCounty';
import type { GetGoogleAutocomplete200SuggestionsItemType } from './getGoogleAutocomplete200SuggestionsItemType';
import type { GetGoogleAutocomplete200SuggestionsItemStreetDisplay } from './getGoogleAutocomplete200SuggestionsItemStreetDisplay';

export type GetGoogleAutocomplete200SuggestionsItem = {
  streetName: GetGoogleAutocomplete200SuggestionsItemStreetName;
  streetNumber: GetGoogleAutocomplete200SuggestionsItemStreetNumber;
  streetPrefix: GetGoogleAutocomplete200SuggestionsItemStreetPrefix;
  streetSuffix: GetGoogleAutocomplete200SuggestionsItemStreetSuffix;
  unitNumber?: GetGoogleAutocomplete200SuggestionsItemUnitNumber;
  /** @minLength 2 */
  city: string;
  stateCode: GetGoogleAutocomplete200SuggestionsItemStateCode;
  county: GetGoogleAutocomplete200SuggestionsItemCounty;
  /**
   * @minLength 2
   * @maxLength 2
   */
  countryCode?: string;
  /**
   * @minLength 5
   * @maxLength 5
   * @pattern ^\d{5}$
   */
  zip: string;
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude: number;
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude: number;
  type: GetGoogleAutocomplete200SuggestionsItemType;
  /** @minLength 1 */
  display: string;
  streetDisplay: GetGoogleAutocomplete200SuggestionsItemStreetDisplay;
};
