/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersUserId200User } from './getUsersUserId200User';

export type GetUsersUserId200 = {
  user: GetUsersUserId200User;
};
