/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */

export type GetUsers200UsersItemRolesItem =
  (typeof GetUsers200UsersItemRolesItem)[keyof typeof GetUsers200UsersItemRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUsers200UsersItemRolesItem = {
  user: 'user',
  admin: 'admin',
} as const;
