/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersUserId200UserRolesItem =
  (typeof GetUsersUserId200UserRolesItem)[keyof typeof GetUsersUserId200UserRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUsersUserId200UserRolesItem = {
  user: 'user',
  admin: 'admin',
} as const;
