/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersUserId200UserCreatedAt } from './getUsersUserId200UserCreatedAt';
import type { GetUsersUserId200UserRolesItem } from './getUsersUserId200UserRolesItem';
import type { GetUsersUserId200UserProfilePictureUrl } from './getUsersUserId200UserProfilePictureUrl';

export type GetUsersUserId200User = {
  id: string;
  createdAt: GetUsersUserId200UserCreatedAt;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /**
   * @minLength 10
   * @maxLength 10
   * @pattern ^\d{10}$
   */
  phone: string;
  email: string;
  /** @minItems 1 */
  roles: GetUsersUserId200UserRolesItem[];
  profilePictureUrl: GetUsersUserId200UserProfilePictureUrl;
};
