/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthSignup200RolesItem =
  (typeof PostAuthSignup200RolesItem)[keyof typeof PostAuthSignup200RolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthSignup200RolesItem = {
  user: 'user',
  admin: 'admin',
} as const;
