/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { PostAddressesBodyStreetName } from './postAddressesBodyStreetName';
import type { PostAddressesBodyStreetNumber } from './postAddressesBodyStreetNumber';
import type { PostAddressesBodyStreetPrefix } from './postAddressesBodyStreetPrefix';
import type { PostAddressesBodyStreetSuffix } from './postAddressesBodyStreetSuffix';
import type { PostAddressesBodyUnitNumber } from './postAddressesBodyUnitNumber';
import type { PostAddressesBodyStateCode } from './postAddressesBodyStateCode';
import type { PostAddressesBodyCounty } from './postAddressesBodyCounty';
import type { PostAddressesBodyLatitude } from './postAddressesBodyLatitude';
import type { PostAddressesBodyLongitude } from './postAddressesBodyLongitude';
import type { PostAddressesBodyType } from './postAddressesBodyType';
import type { PostAddressesBodyDisplay } from './postAddressesBodyDisplay';

export type PostAddressesBody = {
  streetName?: PostAddressesBodyStreetName;
  streetNumber?: PostAddressesBodyStreetNumber;
  streetPrefix?: PostAddressesBodyStreetPrefix;
  streetSuffix?: PostAddressesBodyStreetSuffix;
  unitNumber?: PostAddressesBodyUnitNumber;
  /** @minLength 2 */
  city: string;
  stateCode: PostAddressesBodyStateCode;
  county?: PostAddressesBodyCounty;
  /**
   * @minLength 2
   * @maxLength 2
   */
  countryCode?: string;
  /**
   * @minLength 5
   * @maxLength 5
   * @pattern ^\d{5}$
   */
  zip: string;
  latitude?: PostAddressesBodyLatitude;
  longitude?: PostAddressesBodyLongitude;
  type?: PostAddressesBodyType;
  display?: PostAddressesBodyDisplay;
};
