/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */
import type { PostAddresses201AddressStreetName } from './postAddresses201AddressStreetName';
import type { PostAddresses201AddressStreetNumber } from './postAddresses201AddressStreetNumber';
import type { PostAddresses201AddressStreetPrefix } from './postAddresses201AddressStreetPrefix';
import type { PostAddresses201AddressStreetSuffix } from './postAddresses201AddressStreetSuffix';
import type { PostAddresses201AddressUnitNumber } from './postAddresses201AddressUnitNumber';
import type { PostAddresses201AddressStateCode } from './postAddresses201AddressStateCode';
import type { PostAddresses201AddressCounty } from './postAddresses201AddressCounty';
import type { PostAddresses201AddressType } from './postAddresses201AddressType';
import type { PostAddresses201AddressStreetDisplay } from './postAddresses201AddressStreetDisplay';
import type { PostAddresses201AddressCreatedAt } from './postAddresses201AddressCreatedAt';

export type PostAddresses201Address = {
  streetName: PostAddresses201AddressStreetName;
  streetNumber: PostAddresses201AddressStreetNumber;
  streetPrefix: PostAddresses201AddressStreetPrefix;
  streetSuffix: PostAddresses201AddressStreetSuffix;
  unitNumber?: PostAddresses201AddressUnitNumber;
  /** @minLength 2 */
  city: string;
  stateCode: PostAddresses201AddressStateCode;
  county: PostAddresses201AddressCounty;
  /**
   * @minLength 2
   * @maxLength 2
   */
  countryCode?: string;
  /**
   * @minLength 5
   * @maxLength 5
   * @pattern ^\d{5}$
   */
  zip: string;
  /**
   * @minimum -90
   * @maximum 90
   */
  latitude: number;
  /**
   * @minimum -180
   * @maximum 180
   */
  longitude: number;
  type: PostAddresses201AddressType;
  /** @minLength 1 */
  display: string;
  streetDisplay: PostAddresses201AddressStreetDisplay;
  /** @minLength 1 */
  id: string;
  createdAt: PostAddresses201AddressCreatedAt;
};
