/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */

export type PostAddressesBodyType =
  (typeof PostAddressesBodyType)[keyof typeof PostAddressesBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAddressesBodyType = {
  address: 'address',
  coordinates: 'coordinates',
} as const;
