/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Namespace API
 * API interface. Manually create requests to the API using this UI.
 * OpenAPI spec version: 1.0.0
 */

export type PutUsersUserIdBodyRolesItem =
  (typeof PutUsersUserIdBodyRolesItem)[keyof typeof PutUsersUserIdBodyRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutUsersUserIdBodyRolesItem = {
  user: 'user',
  admin: 'admin',
} as const;
