export const QUEUE_JOB_API_ACTION = 'QUEUE_JOB_API_ACTION';
export const QUEUE_JOB_SENDGRID_EMAIL = 'QUEUE_JOB_SENDGRID_EMAIL';
export const QUEUE_JOB_SLACK_MESSAGES = 'QUEUE_JOB_SLACK_MESSAGES';
export const QUEUE_JOB_TWILIO_TEXT = 'QUEUE_JOB_TWILIO_TEXT';
