
export default {
  POSTED: 'POSTED',
  IS_SUBSCRIBED_TO: 'IS_SUBSCRIBED_TO',
  HAS_TAG: 'HAS_TAG',
  IS_MAIN_TAG: 'IS_MAIN_TAG',
  CHILD_OF: 'CHILD_OF',
  ANSWERED: 'ANSWERED',
  APPRECIATED: 'APPRECIATED',
  VIEWED_TAG: 'VIEWED_TAG',
  HAS_INTEREST: 'HAS_INTEREST',
  INTEREST_CATEGORY: 'INTEREST_CATEGORY'
};
