export const RENDERER_RESPONSE_TYPE_SUCCESS = 'RENDERER_RESPONSE_TYPE_SUCCESS';
export const RENDERER_RESPONSE_TYPE_REDIRECT = 'RENDERER_RESPONSE_TYPE_REDIRECT';
export const RENDERER_RESPONSE_TYPE_NOT_FOUND = 'RENDERER_RESPONSE_TYPE_NOT_FOUND';
export const RENDERER_RESPONSE_TYPE_ERROR = 'RENDERER_RESPONSE_TYPE_ERROR';
