/* eslint-disable max-len */

// Session
export const API_ACTION_LOGIN = 'API_ACTION_LOGIN';
export const API_ACTION_LOGOUT = 'API_ACTION_LOGOUT';
export const API_ACTION_SIGNUP = 'API_ACTION_SIGNUP';
export const API_ACTION_CHECK_LOGIN_EXIST = 'API_ACTION_CHECK_LOGIN_EXIST';
export const API_ACTION_RESET_PASSWORD = 'API_ACTION_RESET_PASSWORD';
export const API_ACTION_GENERATE_RESET_PASSWORD_TOKEN = 'API_ACTION_GENERATE_RESET_PASSWORD_TOKEN';
export const API_ACTION_VERIFY_PHONE_SMS_CODE_REQUESTED = 'API_ACTION_VERIFY_PHONE_SMS_CODE_REQUESTED';
export const API_ACTION_VERIFY_PHONE_SMS_CODE_SUBMIT = 'API_ACTION_VERIFY_PHONE_SMS_CODE_SUBMIT';
export const API_ACTION_VERIFY_ACCOUNT_EXIST = 'API_ACTION_VERIFY_ACCOUNT_EXIST';

// User
export const API_ACTION_USER_GET_BY_ID = 'API_ACTION_USER_GET_BY_ID';
export const API_ACTION_USER_UPDATE = 'API_ACTION_USER_UPDATE';
export const API_ACTION_USER_UPDATE_DEVICE_REGISTRATION_IDS = 'API_ACTION_USER_UPDATE_DEVICE_REGISTRATION_IDS';

// Public
export const API_ACTION_DATATABLE_GET = 'API_ACTION_DATATABLE_GET';
export const API_ACTION_EXPERIMENT_ACTIVE_VARIANTS_UPDATE = 'API_ACTION_EXPERIMENT_ACTIVE_VARIANTS_UPDATE';
export const API_ACTION_BUG_REPORT = 'API_ACTION_BUG_REPORT';

// Admin
export const API_ACTION_ADMIN_UPDATE_ITEM = 'API_ACTION_ADMIN_UPDATE_ITEM';
export const API_ACTION_ADMIN_CREATE_QUEUE_JOB = 'API_ACTION_ADMIN_CREATE_QUEUE_JOB';
export const API_ACTION_ADMIN_RUN_CRON_TASK = 'API_ACTION_ADMIN_RUN_CRON_TASK';

// System
export const API_ACTION_GET_APP_COMMIT_HASH = 'API_ACTION_GET_APP_COMMIT_HASH';
