export enum AddressType {
  Address = 'address',
  Coordinates = 'coordinates',
}

export const streetSuffixMapping = {
  alley: 'aly',
  avenue: 'ave',
  boulevard: 'blvd',
  branch: 'br',
  bridge: 'brg',
  brook: 'brk',
  brooks: 'brks',
  burg: 'bg',
  burgs: 'bgs',
  bypass: 'byp',
  camp: 'cp',
  canyon: 'cyn',
  cape: 'cpe',
  causeway: 'cswy',
  center: 'ctr',
  centers: 'ctrs',
  circle: 'cir',
  circles: 'cirs',
  cliff: 'clf',
  cliffs: 'clfs',
  club: 'clb',
  common: 'cmn',
  corner: 'cor',
  corners: 'cors',
  course: 'crse',
  court: 'ct',
  courts: 'cts',
  cove: 'cv',
  coves: 'cvs',
  creek: 'crk',
  crescent: 'cres',
  crest: 'crst',
  crossing: 'xing',
  crossroad: 'xrd',
  curve: 'curv',
  dale: 'dl',
  dam: 'dm',
  divide: 'dv',
  drive: 'dr',
  drives: 'drs',
  estate: 'est',
  estates: 'ests',
  expressway: 'expy',
  extension: 'ext',
  extensions: 'exts',
  fall: 'fall',
  falls: 'fls',
  ferry: 'fry',
  field: 'fld',
  fields: 'flds',
  flat: 'flt',
  flats: 'flts',
  ford: 'frd',
  fords: 'frds',
  forest: 'frst',
  forge: 'frg',
  forges: 'frgs',
  fork: 'frk',
  forks: 'frks',
  fort: 'ft',
  freeway: 'fwy',
  garden: 'gdn',
  gardens: 'gdns',
  gateway: 'gtwy',
  glen: 'gln',
  glens: 'glns',
  green: 'grn',
  greens: 'grns',
  grove: 'grv',
  groves: 'grvs',
  harbor: 'hbr',
  harbors: 'hbrs',
  haven: 'hvn',
  heights: 'hts',
  highway: 'hwy',
  hill: 'hl',
  hills: 'hls',
  hollow: 'holw',
  inlet: 'inlt',
  island: 'is',
  islands: 'iss',
  isle: 'isle',
  junction: 'jct',
  junctions: 'jcts',
  key: 'ky',
  keys: 'kys',
  knoll: 'knl',
  knolls: 'knls',
  lake: 'lk',
  lakes: 'lks',
  land: 'land',
  landing: 'lndg',
  lane: 'ln',
  light: 'lgt',
  lights: 'lgts',
  loafs: 'lfs',
  lock: 'lck',
  locks: 'lcks',
  lodge: 'ldg',
  loop: 'loop',
  mall: 'mall',
  manor: 'mnr',
  manors: 'mnrs',
  meadow: 'mdw',
  meadows: 'mdws',
  mews: 'mews',
  mill: 'ml',
  mills: 'mls',
  mission: 'msn',
  motorway: 'mtwy',
  mount: 'mt',
  mountain: 'mtn',
  mountains: 'mtns',
  neck: 'nck',
  orchard: 'orch',
  oval: 'ovl',
  overpass: 'opas',
  park: 'park',
  parks: 'parks',
  parkway: 'pkwy',
  parkways: 'pkwys',
  pass: 'pass',
  passage: 'psge',
  path: 'path',
  pike: 'pike',
  place: 'pl',
  plain: 'pln',
  plains: 'plns',
  plaza: 'plz',
  point: 'pt',
  points: 'pts',
  port: 'prt',
  ports: 'prts',
  prairie: 'pr',
  radial: 'radl',
  ramp: 'ramp',
  ranch: 'rnch',
  rapid: 'rpd',
  rapids: 'rpds',
  rest: 'rst',
  ridge: 'rdg',
  ridges: 'rdgs',
  river: 'riv',
  road: 'rd',
  roads: 'rds',
  route: 'rte',
  row: 'row',
  rue: 'rue',
  run: 'run',
  shoal: 'shl',
  shoals: 'shls',
  shore: 'shr',
  shores: 'shrs',
  skyway: 'skwy',
  spring: 'spg',
  springs: 'spgs',
  spur: 'spur',
  spurs: 'spurs',
  square: 'sq',
  squares: 'sqs',
  station: 'sta',
  stravenue: 'stra',
  stream: 'strm',
  street: 'st',
  streets: 'sts',
  summit: 'smt',
  terrace: 'ter',
  throughway: 'trwy',
  trace: 'trce',
  track: 'trak',
  trafficway: 'trfy',
  trail: 'trl',
  tunnel: 'tunl',
  turnpike: 'tpke',
  underpass: 'upas',
  union: 'un',
  unions: 'uns',
  valley: 'vly',
  valleys: 'vlys',
  viaduct: 'via',
  view: 'vw',
  views: 'vws',
  village: 'vlg',
  villages: 'vlgs',
  ville: 'vl',
  vista: 'vis',
  walk: 'walk',
  wall: 'wall',
  way: 'way',
  ways: 'ways',
  well: 'wl',
  wells: 'wls',
};

const longStreetSuffixList = Object.keys(streetSuffixMapping);

export const streetSuffixMappingReversed = longStreetSuffixList.reduce(
  (memo, suffix) => ({
    ...memo,
    [streetSuffixMapping[suffix as keyof typeof streetSuffixMapping]]: suffix,
  }),
  {},
);

const shortStreetSuffixList = Object.keys(streetSuffixMappingReversed);

export const allStreetSuffixes = [...shortStreetSuffixList, ...longStreetSuffixList];

export const streetOrientationAbbreviations = {
  north: 'n',
  west: 'w',
  south: 's',
  east: 'e',
  northwest: 'nw',
  northeast: 'ne',
  southwest: 'sw',
  southeast: 'se',
};

export const streetOrientationAbbreviationsLongList = Object.keys(streetOrientationAbbreviations);

export const streetOrientationAbbreviationsReversed = streetOrientationAbbreviationsLongList.reduce(
  (memo, orientation) => ({
    ...memo,
    [streetOrientationAbbreviations[orientation as keyof typeof streetOrientationAbbreviations]]:
      orientation,
  }),
  {},
);

export const streetOrientationAbbreviationsShortList = Object.keys(
  streetOrientationAbbreviationsReversed,
);

export enum State {
  AL = 'AL',
  AK = 'AK',
  AZ = 'AZ',
  AR = 'AR',
  CA = 'CA',
  CO = 'CO',
  CT = 'CT',
  DE = 'DE',
  FL = 'FL',
  GA = 'GA',
  HI = 'HI',
  ID = 'ID',
  IL = 'IL',
  IN = 'IN',
  IA = 'IA',
  KS = 'KS',
  KY = 'KY',
  LA = 'LA',
  ME = 'ME',
  MD = 'MD',
  MA = 'MA',
  MI = 'MI',
  MN = 'MN',
  MS = 'MS',
  MO = 'MO',
  MT = 'MT',
  NE = 'NE',
  NV = 'NV',
  NH = 'NH',
  NJ = 'NJ',
  NM = 'NM',
  NY = 'NY',
  NC = 'NC',
  ND = 'ND',
  OH = 'OH',
  OK = 'OK',
  OR = 'OR',
  PA = 'PA',
  RI = 'RI',
  SC = 'SC',
  SD = 'SD',
  TN = 'TN',
  TX = 'TX',
  UT = 'UT',
  VT = 'VT',
  VA = 'VA',
  WA = 'WA',
  WV = 'WV',
  WI = 'WI',
  WY = 'WY',
}
